name: action
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - tqdm
  - jupyter
  - notebook
  - pip
  - pytest
  - pytest-cov
  - hypothesis
  - pip:
      - seaborn
      - pandas
